# Generated by Django 3.1.3 on 2020-11-28 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='current_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='source_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sourcing.sourcecode'),
        ),
    ]
