# Generated by Django 3.1.2 on 2021-01-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_auto_20201128_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='source_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
