# Generated by Django 3.1.2 on 2021-01-19 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcing', '0003_auto_20210118_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
