# Generated by Django 3.1.2 on 2021-01-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0004_auto_20210118_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
