# Generated by Django 3.1.2 on 2021-01-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcing', '0005_auto_20210120_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='current_status',
            field=models.CharField(choices=[('UN', 'unprocessed'), ('EX', 'extracted'), ('PAR', 'parsed')], default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='current_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
