# Generated by Django 3.1.2 on 2021-02-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0007_auto_20210129_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='current_status',
            field=models.CharField(blank=True, choices=[('UN', 'unprocessed'), ('EX', 'extracted'), ('PAR', 'parsed')], default='UN', max_length=10),
        ),
    ]
