# Generated by Django 3.1.2 on 2021-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0008_auto_20210203_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='source_code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
