# Generated by Django 3.1.2 on 2021-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0009_auto_20210301_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='current_status',
            field=models.CharField(blank=True, choices=[('SRCM', 'sourced_m'), ('EXTM', 'extracted_m')], default='SRCM', max_length=10),
        ),
    ]
