# Generated by Django 3.0.5 on 2020-09-07 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('source_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('source_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('source_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sourcing.SourceCode')),
            ],
        ),
    ]
