apiVersion: v1
kind: Pod
metadata:
  name: scope-frontend
spec:
  containers:
  - image: ghcr.io/wmgeolab/scope-frontend:latest
    # command: ["/bin/sh", "-c"]
    # args:
         # - "npm run start"
    imagePullPolicy: Always
    name: scope-frontend
    resources:
      limits:
        cpu: 1  # Total 32 cores.
    securityContext:
      runAsGroup: 82656
  imagePullSecrets:
    - name: github-registry-secret
