# Generated by Django 3.1.2 on 2021-03-14 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extracting_m', '0002_extract_source'),
        ('domain', '0004_financialcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_desc', models.CharField(max_length=255)),
                ('activity_date', models.DateField()),
                ('fuzzy_date', models.CharField(blank=True, max_length=30, null=True)),
                ('dollar_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('locations', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('PARM', 'parsed_m'), ('PARQ', 'parsed_q')], max_length=10)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.activitycode')),
                ('activity_subcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.activitysubcode')),
                ('actor_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.actorcode')),
                ('current_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='extracting_m.extract')),
                ('financial_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.financialcode')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.statuscode')),
            ],
        ),
    ]
