# Generated by Django 3.1.2 on 2021-03-12 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('activity_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActorCode',
            fields=[
                ('actor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('actor_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('status_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('fuzzy_date', models.CharField(blank=True, max_length=30, null=True)),
                ('dollar_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('locations', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('EXTQ', 'extracted_q'), ('PARM', 'parsed_m')], max_length=10)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='parsing_m.activitycode')),
                ('actor_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='parsing_m.actorcode')),
            ],
        ),
    ]
