# Generated by Django 3.1.2 on 2021-03-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extracting_m', '0001_initial'),
        ('domain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('activity_date', models.DateField()),
                ('fuzzy_date', models.CharField(blank=True, max_length=30, null=True)),
                ('dollar_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('locations', models.CharField(blank=True, max_length=50, null=True)),
                ('parser_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('PARM', 'parsed_m'), ('PARQ', 'parsed_q')], max_length=10)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.activitycode')),
                ('activity_subcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.activitysubcode')),
                ('actor_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.actorcode')),
                ('actor_rolecode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.actorrole')),
                ('current_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('date_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.datecode')),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='extracting_m.extract')),
                ('financial_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.financialcode')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='domain.statuscode')),
            ],
        ),
    ]
