# Generated by Django 3.1.2 on 2021-03-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='dollar_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
