# Generated by Django 3.1.3 on 2021-03-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
        ('parsing_m', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='parsing_m.activity')),
                ('actor_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='domain.actorcode')),
                ('actor_rolecode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='domain.actorrole')),
            ],
        ),
    ]
