# Generated by Django 3.1.2 on 2021-03-12 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parsing_m', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extracting_m', '0002_auto_20210311_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='extract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='extracting_m.extract'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='parsing_m.statuscode'),
        ),
    ]
