# Generated by Django 3.1.2 on 2021-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_m', '0002_auto_20210311_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='notes',
        ),
        migrations.AlterField(
            model_name='activity',
            name='current_status',
            field=models.CharField(blank=True, choices=[('PARM', 'parsed_m'), ('PARQ', 'parsed_q')], max_length=10),
        ),
    ]
