# Generated by Django 3.1.3 on 2021-03-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_m', '0003_auto_20210324_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_code',
        ),
        migrations.AlterField(
            model_name='actor',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='parsing_m.activity'),
        ),
    ]
