# Generated by Django 3.1.2 on 2021-03-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_m', '0006_auto_20210325_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_subcode',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actor_code',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actor_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='actor_rolecode',
        ),
    ]
