apiVersion: v1
kind: Pod
metadata:
  name: scope-backend
  labels:
    app: scope-backend
spec:
  containers:
  - image: ghcr.io/wmgeolab/backend:latest
    imagePullPolicy: Always
    name: scope-backend
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
    securityContext:
      runAsGroup: 82656
    ports:
      - containerPort: 8000
    env:
      - name: ML_SERVICE_HOSTNAME
        value: ml-api-svc:8000
  imagePullSecrets:
    - name: github-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: scope-backend-svc
spec:
  type: NodePort
  selector:
    app: scope-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30445