# Generated by Django 3.1.2 on 2021-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_extract_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='current_status',
            field=models.CharField(blank=True, choices=[('EXTM', 'extracted_m'), ('EXTQ', 'extracted_q'), ('PARM', 'parsed_m')], max_length=10),
        ),
    ]
