# Generated by Django 3.1.2 on 2021-02-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extraction', '0003_extract_current_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('activity_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActorCode',
            fields=[
                ('actor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('actor_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('status_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('fuzzy_date', models.CharField(blank=True, max_length=30, null=True)),
                ('dollar_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('locations', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='parsing.activitycode')),
                ('actor_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='parsing.actorcode')),
                ('current_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='extraction.extract')),
                ('status_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='parsing.statuscode')),
            ],
        ),
    ]
