# Generated by Django 3.1.2 on 2021-03-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='current_status',
            field=models.CharField(blank=True, choices=[('EXTQ', 'extracted_q'), ('PARM', 'parsed_m')], max_length=10),
        ),
    ]
