# Generated by Django 3.1.2 on 2021-02-04 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsing', '0003_auto_20210129_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
