# Generated by Django 3.1.2 on 2021-03-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('activity_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActorCode',
            fields=[
                ('actor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('actor_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCode',
            fields=[
                ('financial_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('financial_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('source_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('source_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('status_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubcode',
            fields=[
                ('activity_subcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity_subdesc', models.CharField(max_length=255)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.activitycode')),
            ],
        ),
    ]
