# Generated by Django 3.1.2 on 2021-03-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('activity_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActorCode',
            fields=[
                ('actor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('actor_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('status_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerword', models.TextField()),
            ],
        ),
    ]
