# Generated by Django 3.1.3 on 2021-03-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubcode',
            name='activity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_subcodes', to='domain.activitycode'),
        ),
    ]
