# Generated by Django 3.1.2 on 2021-03-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('source_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('source_desc', models.CharField(max_length=255)),
            ],
        ),
    ]
