# Generated by Django 3.1.2 on 2021-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_sourcecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubcode',
            fields=[
                ('activity_subcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity_subdesc', models.CharField(max_length=255)),
            ],
        ),
    ]
