# Generated by Django 3.1.2 on 2021-03-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('EXTM', 'extracted_m'), ('EXTQ', 'extracted_q'), ('PARM', 'parsed_m')], max_length=9)),
            ],
        ),
    ]
