# Generated by Django 3.1.2 on 2021-03-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extracting_m', '0001_initial'),
        ('sourcing_m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracts', to='sourcing_m.source'),
        ),
    ]
