# Generated by Django 3.1.2 on 2021-03-12 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing_m', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extracting_m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extract',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracts', to='sourcing_m.source'),
        ),
    ]
