# Generated by Django 3.1.2 on 2021-03-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
