# Generated by Django 3.1.2 on 2021-04-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing_a', '0002_source_source_relevance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
