# Generated by Django 3.1.2 on 2022-04-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0002_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeBackendAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scopeBackend.user')),
            ],
            bases=('scopeBackend.user',),
        ),
    ]
