# Generated by Django 3.1.2 on 2022-04-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0003_scopebackendadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeBackendAdmin',
        ),
    ]
