# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0005_auto_20220222_1501'),
    ]

    operations = [
        
    ]
