# Generated by Django 4.1.1 on 2024-03-29 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scopeBackend', '0007_tag_workspace_workspaceentries_workspacemembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('entities', models.TextField()),
                ('locations', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.source')),
            ],
        ),
        migrations.AlterField(
            model_name='workspacemembers',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('entities', models.TextField()),
                ('locations', models.TextField()),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('original_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.airesponse')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.workspace')),
            ],
        ),
    ]
