# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-22 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0007_auto_20220222_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user_id',
        ),
    ]
