# Generated by Django 4.1.1 on 2024-04-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0008_airesponse_alter_workspacemembers_member_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.source', unique=True),
        ),
    ]
