# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0008_remove_query_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='name',
        ),
        migrations.AddField(
            model_name='query',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
