# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0009_auto_20220222_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('first', models.CharField(max_length=120)),
                ('last', models.CharField(max_length=120)),
            ],
        ),
    ]
