# Generated by Django 4.1.1 on 2024-10-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0010_workspace_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.workspace')),
            ],
        ),
    ]
