# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0010_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='completed',
        ),
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.User'),
            preserve_default=False,
        ),
    ]
