# Generated by Django 4.1.1 on 2025-03-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0011_workspacequestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacequestions',
            old_name='workspace',
            new_name='workspace_id',
        ),
    ]
