# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0011_auto_20220224_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeBackend',
        ),
    ]
