# Generated by Django 4.1.1 on 2025-03-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0012_rename_workspace_workspacequestions_workspace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponse',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.workspace'),
        ),
        migrations.AlterField(
            model_name='workspacequestions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
