# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0012_delete_scopebackend'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.Query')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.Query')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='sourceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.SourceType'),
        ),
        migrations.AddField(
            model_name='result',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopeBackend.Source'),
        ),
    ]
