# Generated by Django 3.1.2 on 2022-04-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopeBackend', '0014_auto_20220224_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyWord',
        ),
    ]
