name: Build Hurl Docker Image

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # GitHub sets up this token for you
      
    - name: Build and push the Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/hurl:latest ./backend/scopeBackend/hurl/

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/hurl:latest
