name: Run Hurl Tests

on:
  repository_dispatch:
    types: [hurl-tests]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    services:
      backend:
        image: ghcr.io/${{ github.repository_owner }}/backend:latest
        ports:
          - 8000:8000

      - name: Run Hurl Tests
        uses: ghcr.io/Orange-OpenSource/hurl@v1
        with:
          args: "--test --very-verbose 'backend/scopeBackend/Hurl Endpoint Tests.py'"
