name: Run Hurl Tests

on:
  push:
    branches: 
      - master
      - "backend/"
      - "backend/scopeBackend"
  pull_request:
    branches: 
      - master
      - "backend/"
      - "backend/scopeBackend"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Django and Hurl dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y hurl

      - name: Run Django Server
        run: python manage.py runserver &

      - name: Run Hurl Tests
        run: hurl tests/test_endpoints.hurl
