name: Run Hurl Tests

on:
  repository_dispatch:
    types: [hurl-tests]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # GitHub sets up this token for you

      - name: Run tests in container
        uses: docker://ghcr.io/${{ github.repository_owner }}/backend:latest
        with:
          entrypoint: /bin/sh
          args: -c "python3 manage.py runserver & sleep 5 && hurl --test --very-verbose 'Hurl Endpoint Tests.py'"
