name: Run Hurl Tests

on:
  repository_dispatch:
    types: [hurl-tests]
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/${{ github.repository_owner }}/backend:latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run backend server 
        run: python3 manage.py runserver &

      - name: Run Hurl Tests
        run: hurl --test --very-verbose  ‘Hurl Endpoint Tests.py’
