name: Run Hurl Tests

on:
  push:
    branches: 
      - master
      - "backend/"
      - "backend/scopeBackend"
  pull_request:
    branches: 
      - master
      - "backend/"
      - "backend/scopeBackend"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run backend server 
        run: python3 manage.py runserver

      - name: Run Hurl Tests
        run: hurl --test --very-verbose  ‘Hurl Endpoint Tests.py’
