name: Run Hurl Tests

on:
  push:
    branches: 
      - master
      - "backend/**"
  pull_request:
    branches:
      - master
      - "backend/**"
  # these path settings ensure this workflow only executes on a push
  # to this YML itself, or any file in the backend or scopeBackend folders

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
    services:
      backend:
        image: ghcr.io/wmgeolab/backend:latest
        ports:
          - 8000:8000

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Run Hurl Tests
        uses: ghcr.io/Orange-OpenSource/hurl@v1
        with:
          args: "--test --very-verbose 'backend/scopeBackend/Hurl Endpoint Tests.py'"
